"""Persistence for LearnWithPython.

Runs on either SQLite (zero-setup local development) or Postgres, chosen by
environment: set DATABASE_URL and it uses Postgres, otherwise it falls back
to the SQLite file at DATABASE_PATH. Supabase hands you exactly such a URL,
so pointing the app at a hosted database is a one-line .env change and
accounts survive restarts and deploys.

Query functions below are written once, in SQLite dialect, and a thin shim
translates them for Postgres — placeholders, INSERT OR IGNORE, and row
access. The handful of statements that genuinely differ between the two
(date arithmetic, schema DDL) branch on IS_PG explicitly rather than being
regex-mangled, because silent SQL rewriting is how data bugs get made.
"""

import os
import re
import sqlite3
from contextlib import contextmanager
from datetime import date, datetime, timedelta, timezone

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
IS_PG = bool(DATABASE_URL)
DB_PATH = os.environ.get("DATABASE_PATH", "learnwithpython.db")

if IS_PG:
    import psycopg


SCHEMA_SQLITE = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL COLLATE NOCASE,
    email TEXT UNIQUE NOT NULL COLLATE NOCASE,
    password_hash TEXT NOT NULL,
    xp INTEGER NOT NULL DEFAULT 0,
    streak INTEGER NOT NULL DEFAULT 0,
    last_active TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS lesson_progress (
    user_id INTEGER NOT NULL REFERENCES users(id),
    course_slug TEXT NOT NULL,
    lesson_slug TEXT NOT NULL,
    completed_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (user_id, course_slug, lesson_slug)
);

CREATE TABLE IF NOT EXISTS challenge_progress (
    user_id INTEGER NOT NULL REFERENCES users(id),
    challenge_slug TEXT NOT NULL,
    completed_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (user_id, challenge_slug)
);

CREATE TABLE IF NOT EXISTS user_achievements (
    user_id INTEGER NOT NULL REFERENCES users(id),
    achievement_id TEXT NOT NULL,
    earned_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (user_id, achievement_id)
);
"""

# citext gives the case-insensitive username/email lookups that SQLite got
# from COLLATE NOCASE, so "Ana" and "ana" remain the same account.
SCHEMA_PG = """
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username CITEXT UNIQUE NOT NULL,
    email CITEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    xp INTEGER NOT NULL DEFAULT 0,
    streak INTEGER NOT NULL DEFAULT 0,
    last_active TEXT,
    created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    google_sub TEXT,
    avatar_url TEXT,
    google_avatar TEXT,
    display_name TEXT,
    is_admin INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS lesson_progress (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    course_slug TEXT NOT NULL,
    lesson_slug TEXT NOT NULL,
    completed_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (user_id, course_slug, lesson_slug)
);

CREATE TABLE IF NOT EXISTS challenge_progress (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    challenge_slug TEXT NOT NULL,
    completed_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (user_id, challenge_slug)
);

CREATE TABLE IF NOT EXISTS user_achievements (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    achievement_id TEXT NOT NULL,
    earned_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (user_id, achievement_id)
);

CREATE INDEX IF NOT EXISTS lesson_progress_user_idx ON lesson_progress (user_id);
CREATE INDEX IF NOT EXISTS challenge_progress_user_idx ON challenge_progress (user_id);
CREATE INDEX IF NOT EXISTS users_google_sub_idx ON users (google_sub);
"""


# ── Postgres compatibility shim ──────────────────────────────────────
# The query functions speak SQLite. These two classes make the same calls
# work on Postgres so there is one set of queries to read and maintain.

_INSERT_IGNORE = re.compile(r"^\s*INSERT\s+OR\s+IGNORE\s+INTO", re.I)
_INSERT_USERS = re.compile(r"^\s*INSERT\s+INTO\s+users\b", re.I)


class _Row(dict):
    """sqlite3.Row semantics: addressable by column name *or* position.

    psycopg's dict_row only supports names, and several queries here index
    positionally (`fetchone()[0]`), so a plain dict silently breaks them.
    """

    __slots__ = ()

    def __getitem__(self, key):
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)


def _row_factory(cursor):
    cols = [c.name for c in cursor.description or []]
    def make(values):
        return _Row(zip(cols, values))
    return make


class _PgCursor:
    """Cursor with the sqlite3 surface the query functions expect."""

    def __init__(self, cur, lastrowid=None):
        self._cur = cur
        self.lastrowid = lastrowid
        self.rowcount = cur.rowcount

    def fetchone(self):
        return self._cur.fetchone()

    def fetchall(self):
        return self._cur.fetchall()

    def __iter__(self):
        return iter(self._cur)


class _PgConn:
    """Connection wrapper translating SQLite-dialect statements."""

    def __init__(self, conn):
        self._conn = conn

    def execute(self, sql, params=()):
        returning_id = False
        if _INSERT_IGNORE.match(sql):
            sql = _INSERT_IGNORE.sub("INSERT INTO", sql) + " ON CONFLICT DO NOTHING"
        elif _INSERT_USERS.match(sql):
            # stand-in for sqlite3's cursor.lastrowid
            sql += " RETURNING id"
            returning_id = True
        sql = sql.replace("?", "%s")
        cur = self._conn.cursor()
        cur.execute(sql, params)
        last = None
        if returning_id:
            row = cur.fetchone()
            last = row["id"] if row else None
        return _PgCursor(cur, last)

    def commit(self):
        self._conn.commit()

    def close(self):
        self._conn.close()


@contextmanager
def get_db():
    if IS_PG:
        conn = psycopg.connect(DATABASE_URL, row_factory=_row_factory)
        wrapped = _PgConn(conn)
        try:
            yield wrapped
            conn.commit()
        finally:
            conn.close()
        return
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


# Additive, idempotent, and safe to run on every boot.
PG_MIGRATIONS = [
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name TEXT",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS google_avatar TEXT",
]


def init_db():
    if IS_PG:
        with psycopg.connect(DATABASE_URL) as conn:
            with conn.cursor() as cur:
                cur.execute(SCHEMA_PG)
                for stmt in PG_MIGRATIONS:
                    cur.execute(stmt)
            conn.commit()
        return
    with get_db() as db:
        db.executescript(SCHEMA_SQLITE)
        # Lightweight, additive migrations (safe to run every boot).
        cols = {r["name"] for r in db.execute("PRAGMA table_info(users)")}
        if "google_sub" not in cols:
            db.execute("ALTER TABLE users ADD COLUMN google_sub TEXT")
        if "avatar_url" not in cols:
            db.execute("ALTER TABLE users ADD COLUMN avatar_url TEXT")
        if "is_admin" not in cols:
            db.execute("ALTER TABLE users ADD COLUMN is_admin INTEGER NOT NULL DEFAULT 0")
        if "display_name" not in cols:
            db.execute("ALTER TABLE users ADD COLUMN display_name TEXT")
        if "google_avatar" not in cols:
            db.execute("ALTER TABLE users ADD COLUMN google_avatar TEXT")


def _days_ago(n):
    """UTC cutoff formatted the way both backends store timestamps."""
    stamp = datetime.now(timezone.utc) - timedelta(days=n)
    return stamp.strftime("%Y-%m-%d %H:%M:%S")


# ── users ────────────────────────────────────────────────────────────

def create_user(username, email, password_hash):
    with get_db() as db:
        cur = db.execute(
            "INSERT INTO users (username, email, password_hash) VALUES (?, ?, ?)",
            (username, email, password_hash),
        )
        return cur.lastrowid


def find_user(username_or_email):
    with get_db() as db:
        row = db.execute(
            "SELECT * FROM users WHERE username = ? OR email = ?",
            (username_or_email, username_or_email),
        ).fetchone()
        return dict(row) if row else None


def find_user_by_google(google_sub):
    with get_db() as db:
        row = db.execute(
            "SELECT * FROM users WHERE google_sub = ?", (google_sub,)
        ).fetchone()
        return dict(row) if row else None


def create_google_user(username, email, google_sub, avatar_url=None):
    """Create a passwordless account linked to a Google identity."""
    with get_db() as db:
        cur = db.execute(
            "INSERT INTO users (username, email, password_hash, google_sub, avatar_url, google_avatar) "
            "VALUES (?, ?, '', ?, ?, ?)",
            (username, email, google_sub, avatar_url, avatar_url),
        )
        return cur.lastrowid


def link_google_to_user(user_id, google_sub, avatar_url=None):
    with get_db() as db:
        db.execute(
            "UPDATE users SET google_sub = ?, "
            "avatar_url = COALESCE(?, avatar_url), "
            "google_avatar = COALESCE(?, google_avatar) WHERE id = ?",
            (google_sub, avatar_url, avatar_url, user_id),
        )


def update_google_avatar(user_id, url):
    """Store the latest Google profile picture without touching the avatar
    the person actually chose."""
    with get_db() as db:
        db.execute("UPDATE users SET google_avatar = ? WHERE id = ?", (url, user_id))


def get_user(user_id):
    with get_db() as db:
        row = db.execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone()
        return dict(row) if row else None


def add_xp(user_id, amount):
    with get_db() as db:
        db.execute("UPDATE users SET xp = xp + ? WHERE id = ?", (amount, user_id))


def touch_streak(user_id):
    """Update the daily streak; returns the current streak length."""
    today = date.today().isoformat()
    user = get_user(user_id)
    if user["last_active"] == today:
        return user["streak"]
    if user["last_active"]:
        gap = (date.fromisoformat(today) - date.fromisoformat(user["last_active"])).days
        streak = user["streak"] + 1 if gap == 1 else 1
    else:
        streak = 1
    with get_db() as db:
        db.execute(
            "UPDATE users SET streak = ?, last_active = ? WHERE id = ?",
            (streak, today, user_id),
        )
    return streak


# ── progress ─────────────────────────────────────────────────────────

def complete_lesson(user_id, course_slug, lesson_slug):
    """Record completion. Returns True if this was the first completion."""
    with get_db() as db:
        cur = db.execute(
            "INSERT OR IGNORE INTO lesson_progress (user_id, course_slug, lesson_slug) VALUES (?, ?, ?)",
            (user_id, course_slug, lesson_slug),
        )
        return cur.rowcount == 1


def complete_challenge(user_id, challenge_slug):
    with get_db() as db:
        cur = db.execute(
            "INSERT OR IGNORE INTO challenge_progress (user_id, challenge_slug) VALUES (?, ?)",
            (user_id, challenge_slug),
        )
        return cur.rowcount == 1


def get_progress(user_id):
    """Return {course_slug: set(lesson_slugs)} and set of challenge slugs."""
    with get_db() as db:
        lessons = db.execute(
            "SELECT course_slug, lesson_slug FROM lesson_progress WHERE user_id = ?",
            (user_id,),
        ).fetchall()
        challenges = db.execute(
            "SELECT challenge_slug FROM challenge_progress WHERE user_id = ?",
            (user_id,),
        ).fetchall()
    by_course = {}
    for row in lessons:
        by_course.setdefault(row["course_slug"], set()).add(row["lesson_slug"])
    return by_course, {row["challenge_slug"] for row in challenges}


# ── achievements ─────────────────────────────────────────────────────

def get_earned_achievements(user_id):
    with get_db() as db:
        rows = db.execute(
            "SELECT achievement_id, earned_at FROM user_achievements WHERE user_id = ? ORDER BY earned_at",
            (user_id,),
        ).fetchall()
        return {row["achievement_id"]: row["earned_at"] for row in rows}


def grant_achievement(user_id, achievement_id):
    with get_db() as db:
        db.execute(
            "INSERT OR IGNORE INTO user_achievements (user_id, achievement_id) VALUES (?, ?)",
            (user_id, achievement_id),
        )


def leaderboard(limit=10):
    with get_db() as db:
        rows = db.execute(
            "SELECT username, xp, streak FROM users ORDER BY xp DESC, username LIMIT ?",
            (limit,),
        ).fetchall()
        return [dict(r) for r in rows]


def username_taken(username, exclude_user_id=None):
    """True if the name belongs to somebody else. Case-insensitive on both
    backends — citext on Postgres, COLLATE NOCASE on SQLite."""
    with get_db() as db:
        row = db.execute("SELECT id FROM users WHERE username = ?",
                         (username,)).fetchone()
    return bool(row) and row["id"] != exclude_user_id


def update_profile(user_id, username=None, avatar_url=None, display_name=None):
    """Update the fields a learner is allowed to change about themselves."""
    sets, params = [], []
    if username is not None:
        sets.append("username = ?"); params.append(username)
    if avatar_url is not None:
        sets.append("avatar_url = ?"); params.append(avatar_url)
    if display_name is not None:
        sets.append("display_name = ?"); params.append(display_name)
    if not sets:
        return False
    params.append(user_id)
    with get_db() as db:
        db.execute("UPDATE users SET %s WHERE id = ?" % ", ".join(sets), tuple(params))
    return True


def export_user(user_id):
    """Everything held about one person, for the data-export right.

    Deliberately assembled here rather than in a route so the shape cannot
    drift from what delete_user removes.
    """
    with get_db() as db:
        u = db.execute(
            "SELECT id, username, email, xp, streak, last_active, created_at, "
            "google_sub, avatar_url, google_avatar, display_name, is_admin "
            "FROM users WHERE id = ?",
            (user_id,)).fetchone()
        if not u:
            return None
        lessons = db.execute(
            "SELECT course_slug, lesson_slug, completed_at FROM lesson_progress "
            "WHERE user_id = ? ORDER BY completed_at", (user_id,)).fetchall()
        challenges = db.execute(
            "SELECT challenge_slug, completed_at FROM challenge_progress "
            "WHERE user_id = ? ORDER BY completed_at", (user_id,)).fetchall()
        achievements = db.execute(
            "SELECT achievement_id, earned_at FROM user_achievements "
            "WHERE user_id = ? ORDER BY earned_at", (user_id,)).fetchall()
    return {
        "account": dict(u),
        "lesson_progress": [dict(r) for r in lessons],
        "challenge_progress": [dict(r) for r in challenges],
        "achievements": [dict(r) for r in achievements],
    }


def delete_user(user_id):
    """Erase a person and everything attached to them. Returns True if a
    row went.

    Children are removed explicitly rather than relying on ON DELETE
    CASCADE: Postgres declares it, the SQLite schema does not, and SQLite
    only enforces foreign keys when the pragma is on. Doing it by hand
    behaves identically on both.
    """
    with get_db() as db:
        for table in ("lesson_progress", "challenge_progress", "user_achievements"):
            db.execute("DELETE FROM %s WHERE user_id = ?" % table, (user_id,))
        cur = db.execute("DELETE FROM users WHERE id = ?", (user_id,))
        return cur.rowcount > 0


# ── admin portal ─────────────────────────────────────────────────────

def set_admin(username_or_email, is_admin=True):
    """Grant/revoke admin. Returns True if a row was changed."""
    with get_db() as db:
        cur = db.execute(
            "UPDATE users SET is_admin = ? WHERE username = ? OR email = ?",
            (1 if is_admin else 0, username_or_email, username_or_email),
        )
        return cur.rowcount > 0


SORTS = {
    "xp": "u.xp DESC",
    "recent": "COALESCE(u.last_active, u.created_at) DESC",
    "joined": "u.created_at DESC",
    "lessons": "lessons_done DESC",
    "streak": "u.streak DESC",
    "name": "u.username ASC" if IS_PG else "u.username COLLATE NOCASE ASC",
}


def list_members(search="", sort="recent", limit=200, offset=0):
    """Member roster with progress rolled up. Never returns password hashes."""
    order = SORTS.get(sort, SORTS["recent"])
    where, params = "", []
    if search:
        like = "ILIKE" if IS_PG else "LIKE"
        where = f"WHERE u.username {like} ? OR u.email {like} ?"
        params = [f"%{search}%", f"%{search}%"]
    sql = f"""
        SELECT u.id, u.username, u.email, u.xp, u.streak, u.last_active,
               u.created_at, u.is_admin, u.google_sub, u.avatar_url,
               (SELECT COUNT(*) FROM lesson_progress p WHERE p.user_id = u.id)
                   AS lessons_done,
               (SELECT COUNT(*) FROM challenge_progress c WHERE c.user_id = u.id)
                   AS challenges_done,
               (SELECT COUNT(*) FROM user_achievements a WHERE a.user_id = u.id)
                   AS achievements,
               (SELECT MAX(completed_at) FROM lesson_progress p WHERE p.user_id = u.id)
                   AS last_lesson_at
        FROM users u {where}
        ORDER BY {order}
        LIMIT ? OFFSET ?
    """
    with get_db() as db:
        rows = db.execute(sql, (*params, limit, offset)).fetchall()
        total = db.execute(
            f"SELECT COUNT(*) AS n FROM users u {where}", params
        ).fetchone()["n"]
    return [dict(r) for r in rows], total


def member_detail(user_id):
    """Everything the portal shows for one member (no credentials)."""
    with get_db() as db:
        u = db.execute(
            """SELECT id, username, email, xp, streak, last_active, created_at,
                      is_admin, google_sub, avatar_url
               FROM users WHERE id = ?""", (user_id,)
        ).fetchone()
        if not u:
            return None
        lessons = db.execute(
            """SELECT course_slug, lesson_slug, completed_at
               FROM lesson_progress WHERE user_id = ?
               ORDER BY completed_at DESC""", (user_id,)
        ).fetchall()
        challenges = db.execute(
            """SELECT challenge_slug, completed_at
               FROM challenge_progress WHERE user_id = ?
               ORDER BY completed_at DESC""", (user_id,)
        ).fetchall()
        achievements = db.execute(
            "SELECT achievement_id, earned_at FROM user_achievements WHERE user_id = ?"
            " ORDER BY earned_at DESC", (user_id,)
        ).fetchall()
    return {
        "user": dict(u),
        "lessons": [dict(r) for r in lessons],
        "challenges": [dict(r) for r in challenges],
        "achievements": [dict(r) for r in achievements],
    }


def platform_stats():
    """Headline numbers for the admin overview."""
    with get_db() as db:
        one = lambda q, p=(): db.execute(q, p).fetchone()[0]
        return {
            "members": one("SELECT COUNT(*) FROM users"),
            "admins": one("SELECT COUNT(*) FROM users WHERE is_admin = 1"),
            "google_members": one("SELECT COUNT(*) FROM users WHERE google_sub IS NOT NULL"),
            "new_7d": one("SELECT COUNT(*) FROM users WHERE created_at >= ?",
                          (_days_ago(7),)),
            "active_7d": one("SELECT COUNT(*) FROM users WHERE last_active >= ?",
                             ((date.today() - timedelta(days=7)).isoformat(),)),
            "active_today": one("SELECT COUNT(*) FROM users WHERE last_active = ?",
                                (date.today().isoformat(),)),
            "lessons_completed": one("SELECT COUNT(*) FROM lesson_progress"),
            "challenges_completed": one("SELECT COUNT(*) FROM challenge_progress"),
            "total_xp": one("SELECT COALESCE(SUM(xp), 0) FROM users"),
            "learners_with_progress": one(
                "SELECT COUNT(DISTINCT user_id) FROM lesson_progress"),
        }


def signups_by_day(days=14):
    with get_db() as db:
        rows = db.execute(
            """SELECT substr(created_at, 1, 10) AS day, COUNT(*) AS n FROM users
               WHERE created_at >= ?
               GROUP BY day ORDER BY day""", (_days_ago(days),)
        ).fetchall()
    return [dict(r) for r in rows]


def course_engagement():
    """Which courses learners actually work through."""
    with get_db() as db:
        rows = db.execute(
            """SELECT course_slug, COUNT(*) AS completions,
                      COUNT(DISTINCT user_id) AS learners
               FROM lesson_progress GROUP BY course_slug
               ORDER BY completions DESC"""
        ).fetchall()
    return [dict(r) for r in rows]
